name: Trigger GitLab Jobs
on: [push]
jobs:

  build:
    runs-on: self-hosted
    steps:
    - name: Trigger Master Branch
      uses: appleboy/gitlab-ci-action@0.0.1
      with:
        url: "https://gitlab.com/"
        ref: master
        token: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
        project_id: 21914661
