name: trigger gitlab job
on: [push]
jobs:
  trigger-ci-job:
    runs-on: self-hosted
    steps:
      - run: curl -X POST -F token=$TOKEN -F ref=$REF $URL 
        env:
          TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
          REF: main
          URL: https://gitlab.com/api/v4/projects/21914661/trigger/pipeline
